### ISSUE TITLE
Escape/Ignore $ in templates

### ISSUE THREAD

**Issue by etoews** [gliderlabs/sigil#42]
We've been using sigil to template Kubernetes manifests. Sometimes those manifests include references to env vars to be used by the manifest itself and should not be replaced by sigil.

For example look at these lines from [nginx-ingress-controller.yaml](https://github.com/kubernetes/ingress/blob/a8bfdc24277071474263f8f73d30c7066e058e4f/examples/customization/custom-headers/nginx/nginx-ingress-controller.yaml#L41-L53)

```yaml
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --configmap=$(POD_NAMESPACE)/nginx-load-balancer-conf
```

`$(POD_NAMESPACE)` gets replaced by sigil with an empty string but it should really take the value of `POD_NAMESPACE` from the `metadata.namespace` at runtime.

Is there a way to escape/ignore `$` in templates or is that something that would have to be developed?
